In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
data=pd.read_csv("apndcts.csv")
data

       At1    At2    At3    At4    At5    At6    At7  class
0    0.213  0.554  0.207  0.000  0.000  0.749  0.220      1
1    0.458  0.714  0.468  0.111  0.102  0.741  0.436      1
2    0.102  0.518  0.111  0.056  0.022  0.506  0.086      1
3    0.187  0.196  0.105  0.056  0.029  0.133  0.085      1
4    0.236  0.804  0.289  0.111  0.066  0.756  0.241      1
..     ...    ...    ...    ...    ...    ...    ...    ...
101  0.449  0.875  0.523  0.083  0.076  0.920  0.487      0
102  0.102  0.000  0.022  0.000  0.000  0.000  0.017      0
103  0.409  0.875  0.482  0.306  0.259  0.914  0.443      0
104  0.427  0.804  0.474  0.056  0.048  0.836  0.437      0
105  0.462  0.911  0.551  0.167  0.154  0.931  0.500      0

[106 rows x 8 columns]

In [2]:
data=data.dropna(axis=0,how='any')
data

       At1    At2    At3    At4    At5    At6    At7  class
0    0.213  0.554  0.207  0.000  0.000  0.749  0.220      1
1    0.458  0.714  0.468  0.111  0.102  0.741  0.436      1
2    0.102  0.518  0.111  0.056  0.022  0.506  0.086      1
3    0.187  0.196  0.105  0.056  0.029  0.133  0.085      1
4    0.236  0.804  0.289  0.111  0.066  0.756  0.241      1
..     ...    ...    ...    ...    ...    ...    ...    ...
101  0.449  0.875  0.523  0.083  0.076  0.920  0.487      0
102  0.102  0.000  0.022  0.000  0.000  0.000  0.017      0
103  0.409  0.875  0.482  0.306  0.259  0.914  0.443      0
104  0.427  0.804  0.474  0.056  0.048  0.836  0.437      0
105  0.462  0.911  0.551  0.167  0.154  0.931  0.500      0

[106 rows x 8 columns]

In [3]:
predictors=data.iloc[:,0:7]
predictors

       At1    At2    At3    At4    At5    At6    At7
0    0.213  0.554  0.207  0.000  0.000  0.749  0.220
1    0.458  0.714  0.468  0.111  0.102  0.741  0.436
2    0.102  0.518  0.111  0.056  0.022  0.506  0.086
3    0.187  0.196  0.105  0.056  0.029  0.133  0.085
4    0.236  0.804  0.289  0.111  0.066  0.756  0.241
..     ...    ...    ...    ...    ...    ...    ...
101  0.449  0.875  0.523  0.083  0.076  0.920  0.487
102  0.102  0.000  0.022  0.000  0.000  0.000  0.017
103  0.409  0.875  0.482  0.306  0.259  0.914  0.443
104  0.427  0.804  0.474  0.056  0.048  0.836  0.437
105  0.462  0.911  0.551  0.167  0.154  0.931  0.500

[106 rows x 7 columns]

In [4]:
target=data.iloc[:,7]
target

0      1
1      1
2      1
3      1
4      1
      ..
101    0
102    0
103    0
104    0
105    0
Name: class, Length: 106, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
predictors_train,predictors_test,target_train,target_test =train_test_split(
    predictors,target,test_size=0.3,random_state=123)

In [8]:
gnb=GaussianNB()

In [9]:
#First train model/classifier with input dataset
model=gnb.fit(predictors_train,target_train)

In [12]:
#make a prediction using the train model
prediction=model.predict(predictors_test)
print("Predicted Class",prediction)

Predicted Class [0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0]

In [13]:
probs=model.predict_proba(predictors_test)
print("Posterior Probabilities",probs.shape)
print(probs)
print("Class Priors:",model.class_prior_)

Posterior Probabilities (32, 2)
[[9.85612083e-01 1.43879172e-02]
 [9.99944285e-01 5.57154223e-05]
 [9.73891114e-01 2.61088858e-02]
 [9.40825699e-01 5.91743007e-02]
 [3.80104260e-01 6.19895740e-01]
 [9.93291639e-01 6.70836139e-03]
 [7.90565072e-02 9.20943493e-01]
 [4.39004730e-05 9.99956100e-01]
 [2.77345625e-01 7.22654375e-01]
 [9.99999999e-01 1.21289154e-09]
 [9.98989311e-01 1.01068872e-03]
 [8.17393837e-01 1.82606163e-01]
 [9.84609895e-01 1.53901053e-02]
 [7.52693268e-01 2.47306732e-01]
 [1.50784637e-04 9.99849215e-01]
 [9.90066613e-01 9.93338661e-03]
 [9.98864400e-01 1.13560030e-03]
 [9.99332648e-01 6.67351759e-04]
 [9.99993183e-01 6.81675774e-06]
 [9.37395577e-01 6.26044231e-02]
 [9.70769057e-01 2.92309430e-02]
 [9.78957674e-01 2.10423257e-02]
 [3.26049352e-01 6.73950648e-01]
 [9.59361247e-01 4.06387528e-02]
 [6.02637122e-02 9.39736288e-01]
 [9.99985914e-01 1.40859383e-05]
 [9.76697221e-01 2.33027795e-02]
 [9.99756266e-01 2.43733635e-04]
 [1.00000000e+00 1.06059500e-10]
 [5.28392448e-05 9.99947161e-01]
 [9.52751545e-01 4.72484546e-02]
 [9.92092170e-01 7.90783039e-03]]
Class Priors: [0.81081081 0.18918919]

In [15]:
accuracy_score(target_test,prediction,normalize=True)

0.90625